-- Curated expanded-dex habitats for Kanto and Johto.
--
-- This is deliberately a substitution layer, not a ROM-table rewrite: the
-- original encounter decides whether a battle occurs and supplies its level.
-- We only replace the species on a minority of successful rolls. That keeps
-- encounter rates and progression intact on Red/Blue/Yellow, Gold/Silver and
-- map conversions while giving registered Gen 2/3 species stable homes.

local H = {}

local function words(s)
  local out = {}
  for id in tostring(s or ""):gmatch("%S+") do out[#out + 1] = id end
  return out
end

local NATIONAL_4_8 = words([[
TURTWIG GROTLE TORTERRA CHIMCHAR MONFERNO INFERNAPE PIPLUP PRINPLUP EMPOLEON STARLY STARAVIA STARAPTOR BIDOOF BIBAREL KRICKETOT KRICKETUNE SHINX LUXIO LUXRAY BUDEW ROSERADE CRANIDOS RAMPARDOS SHIELDON BASTIODON BURMY WORMADAM MOTHIM COMBEE VESPIQUEN PACHIRISU BUIZEL FLOATZEL CHERUBI CHERRIM SHELLOS GASTRODON AMBIPOM DRIFLOON DRIFBLIM BUNEARY LOPUNNY MISMAGIUS HONCHKROW GLAMEOW PURUGLY CHINGLING STUNKY SKUNTANK BRONZOR BRONZONG BONSLY MIME_JR HAPPINY CHATOT SPIRITOMB GIBLE GABITE GARCHOMP MUNCHLAX RIOLU LUCARIO HIPPOPOTAS HIPPOWDON SKORUPI DRAPION CROAGUNK TOXICROAK CARNIVINE FINNEON LUMINEON MANTYKE SNOVER ABOMASNOW WEAVILE MAGNEZONE LICKILICKY RHYPERIOR TANGROWTH ELECTIVIRE MAGMORTAR TOGEKISS YANMEGA LEAFEON GLACEON GLISCOR MAMOSWINE PORYGON_Z GALLADE PROBOPASS DUSKNOIR FROSLASS ROTOM UXIE MESPRIT AZELF DIALGA PALKIA HEATRAN REGIGIGAS GIRATINA CRESSELIA PHIONE MANAPHY DARKRAI SHAYMIN ARCEUS VICTINI SNIVY SERVINE SERPERIOR TEPIG PIGNITE EMBOAR OSHAWOTT DEWOTT SAMUROTT PATRAT WATCHOG LILLIPUP HERDIER STOUTLAND PURRLOIN LIEPARD PANSAGE SIMISAGE PANSEAR SIMISEAR PANPOUR SIMIPOUR MUNNA MUSHARNA PIDOVE TRANQUILL UNFEZANT BLITZLE ZEBSTRIKA ROGGENROLA BOLDORE GIGALITH WOOBAT SWOOBAT DRILBUR EXCADRILL AUDINO TIMBURR GURDURR CONKELDURR TYMPOLE PALPITOAD SEISMITOAD THROH SAWK SEWADDLE SWADLOON LEAVANNY VENIPEDE WHIRLIPEDE SCOLIPEDE COTTONEE WHIMSICOTT PETILIL LILLIGANT BASCULIN SANDILE KROKOROK KROOKODILE DARUMAKA DARMANITAN MARACTUS DWEBBLE CRUSTLE SCRAGGY SCRAFTY SIGILYPH YAMASK COFAGRIGUS TIRTOUGA CARRACOSTA ARCHEN ARCHEOPS TRUBBISH GARBODOR ZORUA ZOROARK MINCCINO CINCCINO GOTHITA GOTHORITA GOTHITELLE SOLOSIS DUOSION REUNICLUS DUCKLETT SWANNA VANILLITE VANILLISH VANILLUXE DEERLING SAWSBUCK EMOLGA KARRABLAST ESCAVALIER FOONGUS AMOONGUSS FRILLISH JELLICENT ALOMOMOLA JOLTIK GALVANTULA FERROSEED FERROTHORN KLINK KLANG KLINKLANG TYNAMO EELEKTRIK EELEKTROSS ELGYEM BEHEEYEM LITWICK LAMPENT CHANDELURE AXEW FRAXURE HAXORUS CUBCHOO BEARTIC CRYOGONAL SHELMET ACCELGOR STUNFISK MIENFOO MIENSHAO DRUDDIGON GOLETT GOLURK PAWNIARD BISHARP BOUFFALANT RUFFLET BRAVIARY VULLABY MANDIBUZZ HEATMOR DURANT DEINO ZWEILOUS HYDREIGON LARVESTA VOLCARONA COBALION TERRAKION VIRIZION TORNADUS THUNDURUS RESHIRAM ZEKROM LANDORUS KYUREM KELDEO MELOETTA GENESECT CHESPIN QUILLADIN CHESNAUGHT FENNEKIN BRAIXEN DELPHOX FROAKIE FROGADIER GRENINJA BUNNELBY DIGGERSBY FLETCHLING FLETCHINDER TALONFLAME SCATTERBUG SPEWPA VIVILLON LITLEO PYROAR FLABEBE FLOETTE FLORGES SKIDDO GOGOAT PANCHAM PANGORO FURFROU ESPURR MEOWSTIC HONEDGE DOUBLADE AEGISLASH SPRITZEE AROMATISSE SWIRLIX SLURPUFF INKAY MALAMAR BINACLE BARBARACLE SKRELP DRAGALGE CLAUNCHER CLAWITZER HELIOPTILE HELIOLISK TYRUNT TYRANTRUM AMAURA AURORUS SYLVEON HAWLUCHA DEDENNE CARBINK GOOMY SLIGGOO GOODRA KLEFKI PHANTUMP TREVENANT PUMPKABOO GOURGEIST BERGMITE AVALUGG NOIBAT NOIVERN XERNEAS YVELTAL ZYGARDE DIANCIE HOOPA VOLCANION ROWLET DARTRIX DECIDUEYE LITTEN TORRACAT INCINEROAR POPPLIO BRIONNE PRIMARINA PIKIPEK TRUMBEAK TOUCANNON YUNGOOS GUMSHOOS GRUBBIN CHARJABUG VIKAVOLT CRABRAWLER CRABOMINABLE ORICORIO CUTIEFLY RIBOMBEE ROCKRUFF LYCANROC WISHIWASHI MAREANIE TOXAPEX MUDBRAY MUDSDALE DEWPIDER ARAQUANID FOMANTIS LURANTIS MORELULL SHIINOTIC SALANDIT SALAZZLE STUFFUL BEWEAR BOUNSWEET STEENEE TSAREENA COMFEY ORANGURU PASSIMIAN WIMPOD GOLISOPOD SANDYGAST PALOSSAND PYUKUMUKU TYPE_NULL SILVALLY MINIOR KOMALA TURTONATOR TOGEDEMARU MIMIKYU BRUXISH DRAMPA DHELMISE JANGMO_O HAKAMO_O KOMMO_O TAPU_KOKO TAPU_LELE TAPU_BULU TAPU_FINI COSMOG COSMOEM SOLGALEO LUNALA NIHILEGO BUZZWOLE PHEROMOSA XURKITREE CELESTEELA KARTANA GUZZLORD NECROZMA MAGEARNA MARSHADOW POIPOLE NAGANADEL STAKATAKA BLACEPHALON ZERAORA MELTAN MELMETAL GROOKEY THWACKEY RILLABOOM SCORBUNNY RABOOT CINDERACE SOBBLE DRIZZILE INTELEON SKWOVET GREEDENT ROOKIDEE CORVISQUIRE CORVIKNIGHT BLIPBUG DOTTLER ORBEETLE NICKIT THIEVUL GOSSIFLEUR ELDEGOSS WOOLOO DUBWOOL CHEWTLE DREDNAW YAMPER BOLTUND ROLYCOLY CARKOL COALOSSAL APPLIN FLAPPLE APPLETUN SILICOBRA SANDACONDA CRAMORANT ARROKUDA BARRASKEWDA TOXEL TOXTRICITY SIZZLIPEDE CENTISKORCH CLOBBOPUS GRAPPLOCT SINISTEA POLTEAGEIST HATENNA HATTREM HATTERENE IMPIDIMP MORGREM GRIMMSNARL OBSTAGOON PERRSERKER CURSOLA SIRFETCHD MR_RIME RUNERIGUS MILCERY ALCREMIE FALINKS PINCURCHIN SNOM FROSMOTH STONJOURNER EISCUE INDEEDEE MORPEKO CUFANT COPPERAJAH DRACOZOLT ARCTOZOLT DRACOVISH ARCTOVISH DURALUDON DREEPY DRAKLOAK DRAGAPULT ZACIAN ZAMAZENTA ETERNATUS KUBFU URSHIFU ZARUDE REGIELEKI REGIDRAGO GLASTRIER SPECTRIER CALYREX WYRDEER KLEAVOR URSALUNA BASCULEGION SNEASLER OVERQWIL ENAMORUS SPRIGATITO FLORAGATO MEOWSCARADA FUECOCO CROCALOR SKELEDIRGE QUAXLY QUAXWELL QUAQUAVAL LECHONK OINKOLOGNE TAROUNTULA SPIDOPS NYMBLE LOKIX PAWMI PAWMO PAWMOT TANDEMAUS MAUSHOLD FIDOUGH DACHSBUN SMOLIV DOLLIV ARBOLIVA SQUAWKABILLY NACLI NACLSTACK GARGANACL CHARCADET ARMAROUGE CERULEDGE TADBULB BELLIBOLT WATTREL KILOWATTREL MASCHIFF MABOSSTIFF SHROODLE GRAFAIAI BRAMBLIN BRAMBLEGHAST TOEDSCOOL TOEDSCRUEL KLAWF CAPSAKID SCOVILLAIN RELLOR RABSCA FLITTLE ESPATHRA TINKATINK TINKATUFF TINKATON WIGLETT WUGTRIO BOMBIRDIER FINIZEN PALAFIN VAROOM REVAVROOM CYCLIZAR ORTHWORM GLIMMET GLIMMORA GREAVARD HOUNDSTONE FLAMIGO CETODDLE CETITAN VELUZA DONDOZO TATSUGIRI ANNIHILAPE CLODSIRE FARIGIRAF DUDUNSPARCE KINGAMBIT GREAT_TUSK SCREAM_TAIL BRUTE_BONNET FLUTTER_MANE SLITHER_WING SANDY_SHOCKS IRON_TREADS IRON_BUNDLE IRON_HANDS IRON_JUGULIS IRON_MOTH IRON_THORNS FRIGIBAX ARCTIBAX BAXCALIBUR GIMMIGHOUL GHOLDENGO WO_CHIEN CHIEN_PAO TING_LU CHI_YU ROARING_MOON IRON_VALIANT KORAIDON MIRAIDON WALKING_WAKE IRON_LEAVES DIPPLIN POLTCHAGEIST SINISTCHA OKIDOGI MUNKIDORI FEZANDIPITI OGERPON ARCHALUDON HYDRAPPLE GOUGING_FIRE RAGING_BOLT IRON_BOULDER IRON_CROWN TERAPAGOS PECHARUNT
]])

local GEN2 = words([[
CHIKORITA BAYLEEF MEGANIUM CYNDAQUIL QUILAVA TYPHLOSION TOTODILE CROCONAW FERALIGATR SENTRET
FURRET HOOTHOOT NOCTOWL LEDYBA LEDIAN SPINARAK ARIADOS CROBAT CHINCHOU LANTURN
PICHU CLEFFA IGGLYBUFF TOGEPI TOGETIC NATU XATU MAREEP FLAAFFY AMPHAROS
BELLOSSOM MARILL AZUMARILL SUDOWOODO POLITOED HOPPIP SKIPLOOM JUMPLUFF AIPOM SUNKERN
SUNFLORA YANMA WOOPER QUAGSIRE ESPEON UMBREON MURKROW SLOWKING MISDREAVUS UNOWN
WOBBUFFET GIRAFARIG PINECO FORRETRESS DUNSPARCE GLIGAR STEELIX SNUBBULL GRANBULL QWILFISH
SCIZOR SHUCKLE HERACROSS SNEASEL TEDDIURSA URSARING SLUGMA MAGCARGO SWINUB PILOSWINE
CORSOLA REMORAID OCTILLERY DELIBIRD MANTINE SKARMORY HOUNDOUR HOUNDOOM KINGDRA PHANPY
DONPHAN PORYGON2 STANTLER SMEARGLE TYROGUE HITMONTOP SMOOCHUM ELEKID MAGBY MILTANK
BLISSEY RAIKOU ENTEI SUICUNE LARVITAR PUPITAR TYRANITAR LUGIA HO_OH CELEBI
]])

local GEN3 = words([[
TREECKO GROVYLE SCEPTILE TORCHIC COMBUSKEN BLAZIKEN MUDKIP MARSHTOMP SWAMPERT POOCHYENA
MIGHTYENA ZIGZAGOON LINOONE WURMPLE SILCOON BEAUTIFLY CASCOON DUSTOX LOTAD LOMBRE
LUDICOLO SEEDOT NUZLEAF SHIFTRY TAILLOW SWELLOW WINGULL PELIPPER RALTS KIRLIA
GARDEVOIR SURSKIT MASQUERAIN SHROOMISH BRELOOM SLAKOTH VIGOROTH SLAKING NINCADA NINJASK
SHEDINJA WHISMUR LOUDRED EXPLOUD MAKUHITA HARIYAMA AZURILL NOSEPASS SKITTY DELCATTY
SABLEYE MAWILE ARON LAIRON AGGRON MEDITITE MEDICHAM ELECTRIKE MANECTRIC PLUSLE
MINUN VOLBEAT ILLUMISE ROSELIA GULPIN SWALOT CARVANHA SHARPEDO WAILMER WAILORD
NUMEL CAMERUPT TORKOAL SPOINK GRUMPIG SPINDA TRAPINCH VIBRAVA FLYGON CACNEA
CACTURNE SWABLU ALTARIA ZANGOOSE SEVIPER LUNATONE SOLROCK BARBOACH WHISCASH CORPHISH
CRAWDAUNT BALTOY CLAYDOL LILEEP CRADILY ANORITH ARMALDO FEEBAS MILOTIC CASTFORM
KECLEON SHUPPET BANETTE DUSKULL DUSCLOPS TROPIUS CHIMECHO ABSOL WYNAUT SNORUNT
GLALIE SPHEAL SEALEO WALREIN CLAMPERL HUNTAIL GOREBYSS RELICANTH LUVDISC BAGON
SHELGON SALAMENCE BELDUM METANG METAGROSS REGIROCK REGICE REGISTEEL LATIAS LATIOS
KYOGRE GROUDON RAYQUAZA JIRACHI DEOXYS_NORMAL
]])

H.generation = {}
-- v5.16.44: Gen 1 must be part of the same authoritative habitat ecology.
-- Previously these pools began at Johto, so a World substitution could only
-- choose Gen 2/3 and the GEN 1 ONLY scope had nothing reliable to select on
-- a Gen 2 host.
local GEN1 = words([[
BULBASAUR IVYSAUR VENUSAUR CHARMANDER CHARMELEON CHARIZARD SQUIRTLE WARTORTLE BLASTOISE
CATERPIE METAPOD BUTTERFREE WEEDLE KAKUNA BEEDRILL PIDGEY PIDGEOTTO PIDGEOT RATTATA RATICATE
SPEAROW FEAROW EKANS ARBOK PIKACHU RAICHU SANDSHREW SANDSLASH NIDORAN_F NIDORINA NIDOQUEEN
NIDORAN_M NIDORINO NIDOKING CLEFAIRY CLEFABLE VULPIX NINETALES JIGGLYPUFF WIGGLYTUFF ZUBAT
GOLBAT ODDISH GLOOM VILEPLUME PARAS PARASECT VENONAT VENOMOTH DIGLETT DUGTRIO MEOWTH PERSIAN
PSYDUCK GOLDUCK MANKEY PRIMEAPE GROWLITHE ARCANINE POLIWAG POLIWHIRL POLIWRATH ABRA KADABRA
ALAKAZAM MACHOP MACHOKE MACHAMP ONIX BELLSPROUT WEEPINBELL VICTREEBEL TENTACOOL TENTACRUEL GEODUDE
GRAVELER GOLEM PONYTA RAPIDASH SLOWPOKE SLOWBRO MAGNEMITE MAGNETON FARFETCHD DODUO DODRIO SEEL
DEWGONG GRIMER MUK SHELLDER CLOYSTER GASTLY HAUNTER GENGAR DROWZEE HYPNO KRABBY KINGLER VOLTORB
ELECTRODE EXEGGCUTE EXEGGUTOR CUBONE MAROWAK HITMONLEE HITMONCHAN LICKITUNG KOFFING WEEZING RHYHORN
RHYDON CHANSEY TANGELA KANGASKHAN HORSEA SEADRA GOLDEEN SEAKING STARYU STARMIE MR_MIME SCYTHER
JYNX ELECTABUZZ MAGMAR PINSIR TAUROS MAGIKARP GYARADOS LAPRAS DITTO EEVEE VAPOREON JOLTEON FLAREON
PORYGON OMANYTE OMASTAR KABUTO KABUTOPS AERODACTYL SNORLAX ARTICUNO ZAPDOS MOLTRES DRATINI DRAGONAIR
DRAGONITE MEWTWO MEW
]])
for _, id in ipairs(GEN1) do H.generation[id] = 1 end
for _, id in ipairs(GEN2) do H.generation[id] = 2 end
for _, id in ipairs(GEN3) do H.generation[id] = 3 end

local pools = {}
local function pool(id, common, rare)
  pools[id] = { common=words(common), rare=words(rare) }
end

-- Shared habitat pools. Evolved forms appear only in mid/late pools; babies,
-- starters, fossils and legendaries remain gifts, evolutions or world events.
pool("EARLY_FIELD", [[SENTRET HOOTHOOT LEDYBA SPINARAK HOPPIP SUNKERN
 POOCHYENA ZIGZAGOON WURMPLE SEEDOT TAILLOW TORCHIC]],
 [[MAREEP MARILL SURSKIT RALTS SKITTY]])
pool("FOREST", [[LEDYBA SPINARAK HOPPIP PINECO HERACROSS WURMPLE SILCOON
 CASCOON SEEDOT SHROOMISH NINCADA]], [[YANMA SLAKOTH ROSELIA KECLEON]])
pool("MEADOW", [[MAREEP FLAAFFY MARILL HOPPIP SKIPLOOM AIPOM SUNKERN
 GIRAFARIG SNUBBULL STANTLER ZIGZAGOON RALTS SKITTY PLUSLE MINUN
 VOLBEAT ILLUMISE ROSELIA]], [[SMEARGLE MILTANK ABSOL CHIMECHO]])
pool("ROUGH_FIELD", [[FURRET NOCTOWL ARIADOS AIPOM YANMA GLIGAR
 GRANBULL TEDDIURSA PHANPY DONPHAN MIGHTYENA LINOONE SWELLOW BRELOOM
 VIGOROTH ZANGOOSE SEVIPER]], [[URSARING SKARMORY TROPIUS ABSOL]])
pool("CAVE_EARLY", [[DUNSPARCE WOOPER WHISMUR MAKUHITA ARON MEDITITE
 NOSEPASS]], [[SABLEYE MAWILE LARVITAR LUNATONE SOLROCK]])
pool("CAVE_LATE", [[CROBAT MISDREAVUS WOBBUFFET GLIGAR SNEASEL
 PUPITAR LAIRON HARIYAMA SABLEYE MAWILE BALTOY CLAYDOL DUSKULL]],
 [[STEELIX TYRANITAR AGGRON ABSOL BAGON SHELGON BELDUM METANG]])
pool("MOUNTAIN", [[SUDOWOODO GLIGAR SHUCKLE SLUGMA PHANPY DONPHAN
 NUMEL SPOINK SPINDA TRAPINCH CACNEA SWABLU]],
 [[MAGCARGO CAMERUPT FLYGON ALTARIA ABSOL]])
pool("COAST", [[CHINCHOU MARILL CORSOLA REMORAID MANTINE WINGULL
 PELIPPER CARVANHA WAILMER CORPHISH BARBOACH LUVDISC]],
 [[LANTURN OCTILLERY QWILFISH SHARPEDO RELICANTH CLAMPERL]])
pool("DEEP_SEA", [[LANTURN QWILFISH OCTILLERY MANTINE PELIPPER SHARPEDO
 WAILMER WHISCASH CRAWDAUNT CLAMPERL SPHEAL]],
 [[WAILORD MILOTIC HUNTAIL GOREBYSS RELICANTH SEALEO WALREIN]])
pool("COLD", [[SNEASEL SWINUB PILOSWINE DELIBIRD SNORUNT SPHEAL SEALEO]],
 [[SKARMORY GLALIE WALREIN]])
pool("INDUSTRIAL", [[MURKROW HOUNDOUR SLUGMA ELECTRIKE GULPIN SHUPPET]],
 [[HOUNDOOM MAGCARGO MANECTRIC BANETTE BELDUM]])
pool("DESERT_RUIN", [[UNOWN GLIGAR SLUGMA NUMEL TRAPINCH CACNEA
 LUNATONE SOLROCK BALTOY]], [[MAGCARGO FLYGON CACTURNE CLAYDOL]])
pool("SAFARI", [[GIRAFARIG PINECO HERACROSS TEDDIURSA PHANPY STANTLER
 POOCHYENA LOTAD LOMBRE NUZLEAF RALTS SHROOMISH SLAKOTH NINCADA
 ELECTRIKE ROSELIA SPOINK ZANGOOSE SEVIPER KECLEON TROPIUS]],
 [[URSARING DONPHAN MILTANK SHIFTRY LUDICOLO BRELOOM ABSOL BAGON]])
pool("HAUNTED", [[MURKROW MISDREAVUS HOUNDOUR SABLEYE SHUPPET DUSKULL
 CHIMECHO]], [[HOUNDOOM BANETTE DUSCLOPS ABSOL]])

-- v5.16.44: native Kanto species share the ecology instead of living only in
-- the ROM table. This lets Wilds and normal grass use one balanced source.
local GEN1_HABITAT = {
 EARLY_FIELD=words([[PIDGEY RATTATA SPEAROW NIDORAN_F NIDORAN_M MANKEY MEOWTH]]),
 FOREST=words([[CATERPIE WEEDLE PIKACHU ODDISH PARAS VENONAT]]),
 MEADOW=words([[PIDGEY ODDISH BELLSPROUT ABRA DROWZEE EXEGGCUTE TANGELA EEVEE]]),
 ROUGH_FIELD=words([[SPEAROW EKANS SANDSHREW MANKEY PONYTA DODUO CUBONE RHYHORN TAUROS]]),
 CAVE_EARLY=words([[ZUBAT GEODUDE PARAS DIGLETT CLEFAIRY]]),
 CAVE_LATE=words([[ZUBAT GEODUDE MACHOP ONIX CUBONE RHYHORN GASTLY]]),
 MOUNTAIN=words([[GEODUDE MACHOP ONIX PONYTA CUBONE RHYHORN]]),
 COAST=words([[PSYDUCK POLIWAG TENTACOOL SLOWPOKE KRABBY HORSEA GOLDEEN STARYU MAGIKARP]]),
 DEEP_SEA=words([[TENTACOOL SHELLDER KRABBY HORSEA GOLDEEN STARYU MAGIKARP]]),
 COLD=words([[SEEL SHELLDER JYNX LAPRAS]]),
 INDUSTRIAL=words([[MAGNEMITE GRIMER VOLTORB KOFFING ELECTABUZZ]]),
 DESERT_RUIN=words([[SANDSHREW DIGLETT CUBONE RHYHORN]]),
 SAFARI=words([[NIDORAN_F NIDORAN_M PARAS DODUO EXEGGCUTE RHYHORN CHANSEY KANGASKHAN SCYTHER PINSIR TAUROS DRATINI]]),
 HAUNTED=words([[GASTLY CUBONE DROWZEE]]),
}
for habitat,list in pairs(GEN1_HABITAT) do
 local p=pools[habitat]
 if p then for _,id in ipairs(list) do p.common[#p.common+1]=id end end
end

-- 5.13.8: Every bundled Gen 2/3 species must be obtainable when its generation
-- scope is enabled. The hand-curated lists above remain the common ecology;
-- species not already assigned are distributed as rare habitat encounters.
-- This includes starters, babies, fossils and legendaries so no species can
-- become unobtainable on a Red/Blue/Yellow host that has no native Johto/Hoenn
-- gift scripts. Existing curated placements are never duplicated.
local HABITAT_ORDER = {
  "EARLY_FIELD","FOREST","MEADOW","ROUGH_FIELD","CAVE_EARLY",
  "CAVE_LATE","MOUNTAIN","COAST","DEEP_SEA","COLD","INDUSTRIAL",
  "DESERT_RUIN","SAFARI","HAUNTED",
}
local assigned = {}
for _, p in pairs(pools) do
  for _, id in ipairs(p.common or {}) do assigned[id] = true end
  for _, id in ipairs(p.rare or {}) do assigned[id] = true end
end
local function placeMissing(list, offset)
  local n = 0
  for _, id in ipairs(list) do
    if not assigned[id] then
      n = n + 1
      local habitat = HABITAT_ORDER[((n + offset - 2) % #HABITAT_ORDER) + 1]
      local p = pools[habitat]
      p.rare[#p.rare + 1] = id
      assigned[id] = true
    end
  end
end
placeMissing(GEN2, 1)
placeMissing(GEN3, 8)


-- 5.16.2: complete overworld catchability. Every registered Pokemon in The
-- World's merged species pack is assigned to at least one habitat, including
-- evolved forms and compatibility National-Dex species. This is also the
-- authoritative ecology pool used by the Wilds of Kanto bridge.
local FollowerArt = require("mods.the_world.reforged.pokemon.follower_art_registry")
local okPack, PokemonPack = pcall(require, "mods.the_world.reforged.pokemon_data")
if okPack and type(PokemonPack) == "table" and type(PokemonPack.species) == "table" then
  local dexToId = {}
  for id,row in pairs(PokemonPack.species) do
    local dex = type(row)=="table" and tonumber(row.dex) or nil
    if dex then dexToId[math.floor(dex)] = id end
  end
  local already = {}
  for _,p in pairs(pools) do
    for _,id in ipairs(p.common or {}) do already[id]=true end
    for _,id in ipairs(p.rare or {}) do already[id]=true end
  end
  for dex,id in pairs(dexToId) do
    local gen = dex<=151 and 1 or dex<=251 and 2 or dex<=386 and 3 or dex<=493 and 4 or dex<=649 and 5 or dex<=721 and 6 or dex<=809 and 7 or 8
    H.generation[id] = H.generation[id] or gen
    if not already[id] then
      local art = FollowerArt.art and FollowerArt.art[dex]
      local habitat = art and art.habitat or HABITAT_ORDER[((dex - 1) % #HABITAT_ORDER) + 1]
      local p = pools[habitat] or pools.EARLY_FIELD
      p.rare[#p.rare+1] = id
      already[id] = true
    end
  end
end

-- 5.16.4: wild encounter pools contain only unevolved species. Build the
-- set from every evolution target in the merged species database, then filter
-- both The World's habitat substitution and Wilds of Kanto through it. Evolved
-- Pokemon remain obtainable by evolution, gifts/statics and other authored
-- events, but are never selected as ordinary roaming/wild habitat encounters.
H.evolved = {}
local LEGACY_EVOLVED = words([[
IVYSAUR VENUSAUR CHARMELEON CHARIZARD WARTORTLE BLASTOISE METAPOD BUTTERFREE KAKUNA BEEDRILL PIDGEOTTO PIDGEOT RATICATE FEAROW ARBOK PIKACHU RAICHU SANDSLASH NIDORINA NIDOQUEEN NIDORINO NIDOKING CLEFAIRY CLEFABLE NINETALES JIGGLYPUFF WIGGLYTUFF GOLBAT GLOOM VILEPLUME PARASECT VENOMOTH DUGTRIO PERSIAN GOLDUCK PRIMEAPE ARCANINE POLIWHIRL POLIWRATH KADABRA ALAKAZAM MACHOKE MACHAMP WEEPINBELL VICTREEBEL TENTACRUEL GRAVELER GOLEM RAPIDASH SLOWBRO MAGNETON DODRIO DEWGONG MUK CLOYSTER HAUNTER GENGAR HYPNO KINGLER ELECTRODE EXEGGUTOR MAROWAK HITMONLEE HITMONCHAN WEEZING RHYDON SEADRA SEAKING STARMIE JYNX ELECTABUZZ MAGMAR GYARADOS VAPOREON JOLTEON FLAREON OMASTAR KABUTOPS DRAGONAIR DRAGONITE BAYLEEF MEGANIUM QUILAVA TYPHLOSION CROCONAW FERALIGATR FURRET NOCTOWL LEDIAN ARIADOS CROBAT LANTURN TOGETIC XATU FLAAFFY AMPHAROS BELLOSSOM MARILL AZUMARILL POLITOED SKIPLOOM JUMPLUFF SUNFLORA QUAGSIRE ESPEON UMBREON SLOWKING WOBBUFFET FORRETRESS STEELIX GRANBULL SCIZOR URSARING MAGCARGO PILOSWINE OCTILLERY HOUNDOOM KINGDRA DONPHAN PORYGON2 HITMONTOP BLISSEY PUPITAR TYRANITAR GROVYLE SCEPTILE COMBUSKEN BLAZIKEN MARSHTOMP SWAMPERT MIGHTYENA LINOONE SILCOON BEAUTIFLY CASCOON DUSTOX LOMBRE LUDICOLO NUZLEAF SHIFTRY SWELLOW PELIPPER KIRLIA GARDEVOIR MASQUERAIN BRELOOM VIGOROTH SLAKING NINJASK SHEDINJA LOUDRED EXPLOUD HARIYAMA DELCATTY LAIRON AGGRON MEDICHAM MANECTRIC SWALOT SHARPEDO WAILORD CAMERUPT GRUMPIG VIBRAVA FLYGON CACTURNE ALTARIA WHISCASH CRAWDAUNT CLAYDOL CRADILY ARMALDO MILOTIC BANETTE DUSCLOPS GLALIE SEALEO WALREIN HUNTAIL GOREBYSS SHELGON SALAMENCE METANG METAGROSS
]])
for _,id in ipairs(LEGACY_EVOLVED) do H.evolved[id] = true end
if okPack and type(PokemonPack) == "table" and type(PokemonPack.species) == "table" then
  for _,row in pairs(PokemonPack.species) do
    if type(row) == "table" then
      for _,evo in ipairs(row.evolutions or {}) do
        local target = evo.species or evo.target or evo.to
        if target then H.evolved[tostring(target):upper()] = true end
      end
    end
  end
end
function H.isEvolved(id)
  return H.evolved[tostring(id or ""):upper()] == true
end

-- Map names are canonicalised, so ROUTE_1_EAST and MT_MOON_B2F inherit the
-- same habitat without enumerating every ROM/conversion sub-map.
local exact = {
  VIRIDIAN_FOREST="FOREST", ILEX_FOREST="FOREST",
  MT_MOON="CAVE_EARLY", UNION_CAVE="CAVE_EARLY", DARK_CAVE="CAVE_EARLY",
  ROCK_TUNNEL="CAVE_LATE", VICTORY_ROAD="CAVE_LATE",
  DIGLETTS_CAVE="CAVE_EARLY", TOHJO_FALLS="CAVE_LATE",
  SEAFOAM="COLD", ICE_PATH="COLD", WHIRL_ISLANDS="DEEP_SEA",
  SAFARI="SAFARI", SAFARI_ZONE="SAFARI", NATIONAL_PARK="MEADOW",
  POKEMON_TOWER="HAUNTED", BURNED_TOWER="HAUNTED", SPROUT_TOWER="HAUNTED",
  RUINS_OF_ALPH="DESERT_RUIN", POWER_PLANT="INDUSTRIAL",
  POKEMON_MANSION="INDUSTRIAL", SLOWPOKE_WELL="CAVE_EARLY",
}

local kantoRoutes = {
  [1]="EARLY_FIELD",[2]="EARLY_FIELD",[3]="MOUNTAIN",[4]="MOUNTAIN",
  [5]="MEADOW",[6]="MEADOW",[7]="MEADOW",[8]="ROUGH_FIELD",
  [9]="MOUNTAIN",[10]="MOUNTAIN",[11]="INDUSTRIAL",[12]="COAST",
  [13]="COAST",[14]="ROUGH_FIELD",[15]="ROUGH_FIELD",[16]="ROUGH_FIELD",
  [17]="ROUGH_FIELD",[18]="ROUGH_FIELD",[19]="COAST",[20]="DEEP_SEA",
  [21]="COAST",[22]="EARLY_FIELD",[23]="CAVE_LATE",[24]="MEADOW",
  [25]="MEADOW",[26]="ROUGH_FIELD",[27]="ROUGH_FIELD",[28]="CAVE_LATE",
}
local johtoRoutes = {
  [29]="EARLY_FIELD",[30]="EARLY_FIELD",[31]="EARLY_FIELD",
  [32]="COAST",[33]="FOREST",[34]="MEADOW",[35]="MEADOW",
  [36]="MEADOW",[37]="FOREST",[38]="ROUGH_FIELD",[39]="ROUGH_FIELD",
  [40]="COAST",[41]="DEEP_SEA",[42]="MOUNTAIN",[43]="COAST",
  [44]="ROUGH_FIELD",[45]="CAVE_LATE",[46]="MOUNTAIN",[47]="COAST",
  [48]="SAFARI",
}

-- Spread later-generation species deterministically across every habitat.
-- They enter the rare side, preserving native/early-generation identity while
-- making Gen 4-8 genuinely encounterable when the scope permits them.
for i,id in ipairs(NATIONAL_4_8) do
  local dex=386+i
  H.generation[id]=dex<=493 and 4 or dex<=649 and 5 or dex<=721 and 6 or dex<=809 and 7 or 8
  local habitat=HABITAT_ORDER[((dex-1)%#HABITAT_ORDER)+1]
  local target=pools[habitat] or pools.EARLY_FIELD
  target.rare[#target.rare+1]=id
end

local function canonical(mapId)
  return tostring(mapId or ""):upper():gsub("[^A-Z0-9]+", "_")
end

function H.poolFor(mapId)
  local id = canonical(mapId)
  for key, habitat in pairs(exact) do
    if id:find(key, 1, true) then return pools[habitat], habitat end
  end
  local n = tonumber(id:match("ROUTE_(%d+)"))
  local habitat = n and (johtoRoutes[n] or kantoRoutes[n])
  return habitat and pools[habitat] or nil, habitat
end

function H.scope()
  local value
  pcall(function()
    local Game = require("src.core.Game")
    local save = Game and Game.mods and Game.mods.save
    if save and save.get then value = save:get("world_content_scope") end
  end)
  -- Normal route uses the active mod save in install(), which passes scope.
  return value or "gen1_gen2_gen3_gen4_gen5_gen6_gen7_gen8"
end

local SCOPE_GEN={gen1=1,gen1_gen2=2,gen1_gen2_gen3=3,gen1_gen2_gen3_gen4=4,gen1_gen2_gen3_gen4_gen5=5,gen1_gen2_gen3_gen4_gen5_gen6=6,gen1_gen2_gen3_gen4_gen5_gen6_gen7=7,gen1_gen2_gen3_gen4_gen5_gen6_gen7_gen8=8}
function H.allows(id, scope)
  local generation = H.generation[id]
  if not generation then return false end
  return generation <= (SCOPE_GEN[scope or "gen1_gen2_gen3_gen4_gen5_gen6_gen7_gen8"] or 8)
end

-- 5.16.41: refresh habitats from the live merged registry, not only The World's
-- bundled Gen2/3 pack. Compatibility mods can register Gen4-8 species after this
-- module loads; previously those Pokemon were invisible to the habitat system and
-- the ALL INCLUDED setting effectively stopped at Hoenn.
local runtimeSeen = {}
local function refreshRuntimeSpecies()
  local okG, Game = pcall(require, "src.core.Game")
  local mons = okG and Game and Game.data and Game.data.pokemon
  if type(mons) ~= "table" then return end
  local evolvedNow = {}
  for _,row in pairs(mons) do
    if type(row)=="table" then
      for _,evo in ipairs(row.evolutions or {}) do
        local target=evo.species or evo.target or evo.to
        if target then evolvedNow[tostring(target):upper()]=true end
      end
    end
  end
  for id,row in pairs(mons) do
    local key=tostring(id):upper()
    if type(row)=="table" and not runtimeSeen[key] then
      local dex=tonumber(row.dex or row.nationalDex or row.national_dex)
      if dex then
        local gen=dex<=151 and 1 or dex<=251 and 2 or dex<=386 and 3 or dex<=493 and 4 or dex<=649 and 5 or dex<=721 and 6 or dex<=809 and 7 or 8
        H.generation[key]=gen
        if evolvedNow[key] then H.evolved[key]=true end
        local habitat=(row.worldHabitat or row.habitat)
        if not pools[habitat] then habitat=HABITAT_ORDER[((math.floor(dex)-1)%#HABITAT_ORDER)+1] end
        local target=pools[habitat] or pools.EARLY_FIELD
        local found=false
        for _,x in ipairs(target.common or {}) do if x==key then found=true break end end
        if not found then for _,x in ipairs(target.rare or {}) do if x==key then found=true break end end end
        if not found and not H.evolved[key] then target.rare[#target.rare+1]=key end
      end
      runtimeSeen[key]=true
    end
  end
end

function H.choose(mapId, scope, exists, rng)
  refreshRuntimeSpecies()
  local p, habitat = H.poolFor(mapId)
  if not p then return nil end
  local common, rare = {}, {}
  for _, id in ipairs(p.common or {}) do
    if H.allows(id, scope) and not H.isEvolved(id) and exists(id) then common[#common + 1] = id end
  end
  for _, id in ipairs(p.rare or {}) do
    if H.allows(id, scope) and not H.isEvolved(id) and exists(id) then rare[#rare + 1] = id end
  end
  local function roll()
    local v = rng and rng() or love and love.math and love.math.random() or math.random()
    return tonumber(v) or 0
  end
  local list = #rare > 0 and roll() < 0.12 and rare or common
  if #list == 0 then list = #rare > 0 and rare or nil end
  if not list then return nil end
  local i = math.max(1, math.min(#list, math.floor(roll() * #list) + 1))
  return list[i], habitat
end

return H
