local W={}

W.AI_ROWS={

  {key="worldShark",label="WORLD SHARK",type="choice",default="off",
    choices={{"ON","on"},{"OFF","off"}},
    help="Enables The World's integrated GameShark tools. OFF hides WORLD SHARK from the Start menu and suspends all cheat effects."},
  {key="worldContentScope",label="WHICH POKEMON CAN APPEAR?",type="choice",default="gen1_gen2_gen3_gen4_gen5_gen6_gen7_gen8",
    choices={{"KANTO ONLY (GEN 1)","gen1"},{"KANTO + JOHTO (GEN 1-2)","gen1_gen2"},{"THROUGH HOENN (GEN 1-3)","gen1_gen2_gen3"},{"THROUGH SINNOH (GEN 1-4)","gen1_gen2_gen3_gen4"},{"THROUGH UNOVA (GEN 1-5)","gen1_gen2_gen3_gen4_gen5"},{"THROUGH KALOS (GEN 1-6)","gen1_gen2_gen3_gen4_gen5_gen6"},{"THROUGH ALOLA (GEN 1-7)","gen1_gen2_gen3_gen4_gen5_gen6_gen7"},{"ALL INCLUDED (GEN 1-8)","gen1_gen2_gen3_gen4_gen5_gen6_gen7_gen8"}},
    help="Distributes registered Gen 2 and Gen 3 Pokemon across appropriate Kanto and Johto habitats while preserving native encounter levels and rates."},
  {key="worldEncounterControl",label="WILD ENCOUNTERS",type="choice",default="auto",
    choices={{"AUTO / COMPATIBLE","auto"},{"THE WORLD","world"},{"EXTERNAL / VANILLA","external"}},
    help="Who owns ordinary wild encounters. AUTO yields to compatible encounter mods such as All Pokemon Catchable 151. EXTERNAL / VANILLA disables The World encounter substitutions, generation filtering, weather species bias, WX wild substitution and encounter-rate changes while leaving weather visuals and the rest of The World active."},
  {key="worldWonderTrader",label="WONDER TRADER",type="choice",default="on",
    choices={{"ON","on"},{"OFF","off"}},
    help="Controls the player-facing Wonder Trader attendants in Pokemon Centers. OFF prevents them from being added. Restart after changing this option."},
  {key="wonderTradeLegendary",label="WT: ALLOW LEGENDARY",type="choice",default="on",
    choices={{"ON","on"},{"OFF","off"}},
    help="Allows Legendary Pokemon to be sent and received through Wonder Trade. OFF removes them from the Wonder Trade pool and rejects Legendary Pokemon offered by the player."},
  {key="wonderTradePseudoLegendary",label="WT: ALLOW PSEUDO",type="choice",default="on",
    choices={{"ON","on"},{"OFF","off"}},
    help="Allows pseudo-Legendary Pokemon and their evolutionary families in Wonder Trade. OFF excludes those families from sending and receiving."},
  {key="wonderTradeMythical",label="WT: ALLOW MYTHICAL",type="choice",default="on",
    choices={{"ON","on"},{"OFF","off"}},
    help="Allows Mythical Pokemon to be sent and received through Wonder Trade. OFF removes them from the Wonder Trade pool and rejects Mythical Pokemon offered by the player."},
  {key="worldAbilities",label="ABILITIES",type="choice",default="on",
    choices={{"ON","on"},{"OFF","off"}},
    help="Pokemon abilities embedded directly in The World. OFF keeps species data but disables ability battle effects."},
  {key="worldHeldItems",label="HELD ITEMS",type="choice",default="off",
    choices={{"ON","on"},{"OFF","off"}},
    help="Gen 2/3 held-item effects and wild held items. Existing held items remain save-safe when OFF."},
  {key="worldModernMoves",label="MOVES THROUGH GEN 8",type="choice",default="on",
    choices={{"ON","on"},{"OFF","off"}},
    help="Enables level-up learnsets and move mechanics through Generation 8. OFF keeps the move roster registered for save safety but restores generation-native learnsets."},
  {key="worldModernTypes",label="DARK/STEEL/FAIRY",type="choice",default="on",
    choices={{"ON","on"},{"OFF","off"}},
    help="Expanded type support required by later-generation Pokemon."},
  {key="worldSpecialSplit",label="SP.ATK / SP.DEF",type="choice",default="on",
    choices={{"ON","on"},{"OFF","off"}},
    help="Splits SPECIAL into separate Special Attack and Special Defence stats. Per-save; OFF preserves the original rules."},
  {key="worldPhysicalSplit",label="PHYSICAL/SPECIAL SPLIT",type="choice",default="off",
    choices={{"ON","on"},{"OFF","off"}},
    help="Uses each move's own physical or special category instead of deciding by type. The battle move menu shows PHYS, SPEC or STATUS. Per-save; OFF preserves Gen 1/2 type categories."},
  {key="worldShinyEffect",label="MODERN SHINY EFFECT",type="choice",default="on",
    choices={{"ON","on"},{"OFF","off"}},
    help="Plays a modern sparkle and flash when a shiny Pokemon enters battle in Gen 1 or Gen 2."},
  {key="battle_exp_bar",label="GEN 1 EXP BAR",type="toggle",default=true,
    help="Shows the Gen 2-style EXP bar during Red, Blue and Yellow battles. Gold, Silver and Crystal use their native EXP bar."},
  {key="achievement_notifications",label="ACHIEVEMENT POPUPS",type="toggle",default=true,
    help="Shows small colour-coded achievement notifications at the top-right. Achievement progress is still recorded when OFF."},
  {key="worldAI",label="AI TRAINERS",type="choice",default="on",
    choices={{"ON","on"},{"OFF","off"}},
    help="Master switch for autonomous Rivals, Team Rocket, Pokemon Rangers, rival wars and AI tournaments."},
  {key="simulate_unvisited_regions",label="SIMULATE UNVISITED REGIONS",type="choice",default="on",
    choices={{"ON","on"},{"OFF","off"}},
    help="ON lets rivals continue travelling, training and challenging Gyms in regions the player has not visited. The starting region uses its normal level curve; every other region uses the advanced Lv40-100 curve. Sevii is low-level only when it is the starting region."},
  {key="rivals",label="RIVALS",type="choice",default="all",
    choices={{"OFF","off"},{"TWO","two"},{"ALL","all"}}},
  {key="encounters",label="RIVAL DUELS",type="toggle",default=true},
  {key="rival_nameplates",label="RIVAL NAMEPLATES",type="toggle",default=true,
    help="Shows each materialized rival's name above their overworld sprite. Turn OFF for the original uncluttered overworld."},
  {key="three_badge_rule",label="THREE BADGE RULE",type="toggle",default=true,
    help="ON keeps rivals within three badges of the player. OFF removes the player-relative badge cap so rivals can race through their own campaign as quickly as their teams, travel and battles allow."},
  {key="pace",label="WORLD PACE",type="choice",default="normal",
    choices={{"SLOW","slow"},{"NORMAL","normal"},{"FAST","fast"}}},
  {key="performance",label="WALKING COST",type="choice",default="balanced",
    choices={{"LOW","low"},{"BALANCED","balanced"},{"FULL","full"}}},
  {key="relationships",label="RIVAL BONDS",type="toggle",default=true},
  {key="sightings",label="RIVAL SIGHTINGS",type="toggle",default=true},
  {key="life_paths",label="RIVAL LIFE PATHS",type="toggle",default=true},
  {key="news_ticker",label="NEWS TICKER",type="toggle",default=true},
  {key="ticker_spam",label="TICKER VOLUME",type="choice",default="normal",
    choices={{"QUIET","quiet"},{"NORMAL","normal"},{"FULL","full"}}},
  {key="rocket_pace",label="ROCKET SPREAD",type="choice",default="normal",
    choices={{"SLOW","slow"},{"NORMAL","normal"},{"AGGRESSIVE","aggressive"}}},
  {key="clone_lag_guard",label="CLONE LAG GUARD",type="toggle",default=true},
  {key="large_pokegear",label="LARGE RIVALGEAR TEXT",type="toggle",default=false},
  {key="debug",label="WORLD AI DEBUG",type="toggle",default=false},
  {key="starting_region",label="STARTING REGION",type="choice",default="kanto",
    choices={{"KANTO","kanto"},{"JOHTO","johto"},{"SEVII ISLANDS","sevii"},{"ALMIA","almia"},{"SINNOH","sinnoh"},{"HOENN","hoenn"}},
    help="Gen 1 new games: begin in Kanto, Johto, the Sevii Islands, Almia, Sinnoh, or Hoenn. Existing saves default to Kanto."},
  {key="johto_postgame",label="JOHTO REGION",type="toggle",default=false,
    help="Gen 1 only. Makes Johto available. A Johto-start new game enables it automatically; Kanto-start saves use it as the post-Champion level 40-100 campaign. Restart after changing."},
  {key="custom_kanto_districts",label="KANTO DISTRICTS",type="toggle",default=true,
    help="Adds native-style Kanto districts such as Pallet Meadows and Cinnabar Terrace. OFF leaves vanilla Kanto maps and Pokemon Centers untouched. Restart the game after changing this option."},
  {key="rival_debug_editor",label="RIVAL DEBUG EDITOR",type="toggle",default=false,
    help="Adds a DEBUG EDIT option when talking to a rival. Allows live editing of name, gender, overworld sprite, personality, life/career path and personal goal without replacing the rival or erasing its history."},
}
local TAB_BY_KEY={
  worldShark="world",worldContentScope="world",worldEncounterControl="world",worldWonderTrader="world",wonderTradeLegendary="world",wonderTradePseudoLegendary="world",wonderTradeMythical="world",starting_region="world",johto_postgame="world",custom_kanto_districts="world",pace="world",performance="world",news_ticker="world",ticker_spam="world",
  worldAI="rivals",simulate_unvisited_regions="rivals",rivals="rivals",encounters="rivals",rival_nameplates="rivals",three_badge_rule="rivals",relationships="rivals",sightings="rivals",life_paths="rivals",rocket_pace="rivals",rival_debug_editor="rivals",clone_lag_guard="rivals",large_pokegear="rivals",debug="rivals",
  worldAbilities="game",worldHeldItems="game",worldModernMoves="game",worldModernTypes="game",worldSpecialSplit="game",worldPhysicalSplit="game",
  worldShinyEffect="game",
  battle_exp_bar="game",achievement_notifications="game",
}
function W.rows()
  local out={}
  for _,r in ipairs(W.AI_ROWS) do
    local c={} for k,v in pairs(r) do c[k]=v end
    c.tab=c.tab or TAB_BY_KEY[c.key]
    out[#out+1]=c
  end
  return out
end
return W
